### ISSUE TITLE
Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by sinistra** [matyunya/smelte#186]
I have recently started to receive the following error message every time I execute 'npm run build'...
```
risk - There are upcoming breaking changes: removeDeprecatedGapUtilities, purgeLayersByDefault
risk - We highly recommend opting-in to these changes now to simplify upgrading Tailwind in the future.
risk - https://tailwindcss.com/docs/upcoming-changes
[!] (plugin postcss) Error: ENOTDIR: not a directory, scandir 'src/components/Dropfile.svelte'
node_modules/smelte/src/tailwind.css
Error: ENOTDIR: not a directory, scandir 'src/components/Dropfile.svelte'
    at Object.readdirSync (fs.js:871:3)
    at /Users/paul/projects/loftop-svelte/node_modules/smelte/src/utils/css-extractor.js:47:23
    at Array.filter (<anonymous>)
    at /Users/paul/projects/loftop-svelte/node_modules/smelte/src/utils/css-extractor.js:47:8
    at Array.map (<anonymous>)
    at getComponentCodes (/Users/paul/projects/loftop-svelte/node_modules/smelte/src/utils/css-extractor.js:44:23)
    at /Users/paul/projects/loftop-svelte/node_modules/smelte/src/utils/css-extractor.js:119:20
    at Array.map (<anonymous>)
    at extractor (/Users/paul/projects/loftop-svelte/node_modules/smelte/src/utils/css-extractor.js:117:46)
    at Purgecss.extractSelectors (/Users/paul/projects/loftop-svelte/node_modules/purgecss/lib/purgecss.js:739:70)

npm ERR! code ELIFECYCLE 
```
It does not occur with 'npm run dev'.

versions are...
   "smelte": "^1.0.16",
    "svelte": "^3.29.0",

if I go through the process of renaming my component and all references to it, the error moves to another component.

has anyone experienced this?

**Comment by sinistra** [comment]
commenting out line 41 of src/utils/css-extractor.js fixes this.

**Comment by matyunya** [comment]
Please try with 1.0.17. Should be fixed now.

**Comment by sinistra** [comment]
upgrade to 1.0.17 resolves this issue
