### ISSUE TITLE
✗ server Errors

### ISSUE THREAD

**Issue by bordunosp** [matyunya/smelte#54]
1) npx degit matyunya/smelte-sapper-template my-svelte-project
2) cd my-svelte-project
3) yarn && yarn upgrade
4) yarn dev

```
✗ server
ENOENT: no such file or directory, open '/home/bordunos/projects/events-enjoy/tmp-smelte/static/global.css'
(node:8208) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '[PROJECT_PATH]/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
```

**Comment by matyunya** [comment]
Thanks for your report! The problem should be gone now.
